name: coinz_app
description: "coinz_app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  pinput: ^5.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/patterns/pattern_1.svg
    - assets/svg/patterns/pattern_2.svg
    - assets/svg/patterns/pattern_3.svg
    - assets/svg/patterns/pattern_4.svg
    - assets/svg/patterns/pattern_5.svg